complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
  MatchingDeclarationName:
    active: false

formatting:
  Filename:
    active: false

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
